# -*- coding: utf-8 -*-
from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(925, 665)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("background-color: rgb(228, 255, 248);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButtonOpenPort = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonOpenPort.setGeometry(QtCore.QRect(0, 10, 161, 25))
        self.pushButtonOpenPort.setObjectName("pushButtonOpenPort")
        self.pushButtonClosePort = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonClosePort.setGeometry(QtCore.QRect(640, 10, 161, 25))
        self.pushButtonClosePort.setObjectName("pushButtonClosePort")
        self.groupBoxAxisSpeed = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxAxisSpeed.setGeometry(QtCore.QRect(0, 40, 391, 151))
        self.groupBoxAxisSpeed.setObjectName("groupBoxAxisSpeed")
        self.label = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_3.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBoxAxisSpeed)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.label_5.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_5.setObjectName("label_5")
        self.textEditXSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditXSpeedSet.setGeometry(QtCore.QRect(80, 30, 91, 31))
        self.textEditXSpeedSet.setObjectName("textEditXSpeedSet")
        self.textEditYSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditYSpeedSet.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.textEditYSpeedSet.setObjectName("textEditYSpeedSet")
        self.textEditZSpeedSet = QtWidgets.QTextEdit(self.groupBoxAxisSpeed)
        self.textEditZSpeedSet.setGeometry(QtCore.QRect(80, 110, 91, 31))
        self.textEditZSpeedSet.setObjectName("textEditZSpeedSet")
        self.pushButtonSpeedSet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedSet.setGeometry(QtCore.QRect(180, 70, 89, 41))
        self.pushButtonSpeedSet.setObjectName("pushButtonSpeedSet")
        self.pushButtonSpeedGet = QtWidgets.QPushButton(self.groupBoxAxisSpeed)
        self.pushButtonSpeedGet.setGeometry(QtCore.QRect(290, 70, 89, 41))
        self.pushButtonSpeedGet.setObjectName("pushButtonSpeedGet")
        self.groupBoxMoveCoordiante = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxMoveCoordiante.setGeometry(QtCore.QRect(0, 180, 851, 191))
        self.groupBoxMoveCoordiante.setObjectName("groupBoxMoveCoordiante")
        self.label_9 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 67, 17))
        self.label_9.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 67, 17))
        self.label_10.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 67, 17))
        self.label_11.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_11.setObjectName("label_11")


        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(780, 370, 111, 151))
        self.groupBox.setObjectName("groupBox")
        self.textEditSetPosition = QtWidgets.QTextEdit(self.groupBox)
        self.textEditSetPosition.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.textEditSetPosition.setObjectName("textEditSetPosition")
        self.pushButtonSetPosition = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonSetPosition.setGeometry(QtCore.QRect(10, 80, 89, 41))
        self.pushButtonSetPosition.setObjectName("pushButtonSetPosition")

        self.textEditxMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxMove.setGeometry(QtCore.QRect(80, 60, 91, 31))
        self.textEditxMove.setObjectName("textEditxMove")
        self.textEdityMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEdityMove.setGeometry(QtCore.QRect(80, 100, 91, 31))
        self.textEdityMove.setObjectName("textEdityMove")
        self.textEditzMove = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditzMove.setGeometry(QtCore.QRect(80, 140, 91, 31))
        self.textEditzMove.setObjectName("textEditzMove")
        self.pushButtonMovex = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovex.setGeometry(QtCore.QRect(190, 60, 75, 19))
        self.pushButtonMovex.setObjectName("pushButtonMovex")
        self.pushButtonMovey = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovey.setGeometry(QtCore.QRect(190, 100, 75, 20))
        self.pushButtonMovey.setObjectName("pushButtonMovey")
        self.pushButtonMovez = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonMovez.setGeometry(QtCore.QRect(190, 140, 75, 19))
        self.pushButtonMovez.setObjectName("pushButtonMovez")
        self.pushButtonGetx = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetx.setGeometry(QtCore.QRect(290, 60, 75, 19))
        self.pushButtonGetx.setObjectName("pushButtonGetx")
        self.pushButtonGety = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGety.setGeometry(QtCore.QRect(290, 100, 75, 19))
        self.pushButtonGety.setObjectName("pushButtonGety")
        self.pushButtonGetz = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetz.setGeometry(QtCore.QRect(290, 140, 75, 19))
        self.pushButtonGetz.setObjectName("pushButtonGetz")
        self.labelSensorX = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.labelSensorX.setGeometry(QtCore.QRect(390, 60, 91, 21))
        self.labelSensorX.setText("")
        self.labelSensorX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSensorX.setObjectName("labelSensorX")
        self.labelSensorY = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.labelSensorY.setGeometry(QtCore.QRect(390, 100, 91, 21))
        self.labelSensorY.setText("")
        self.labelSensorY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSensorY.setObjectName("labelSensorY")
        self.labelSensorZ = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.labelSensorZ.setGeometry(QtCore.QRect(390, 140, 91, 21))
        self.labelSensorZ.setText("")
        self.labelSensorZ.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSensorZ.setObjectName("labelSensorZ")
        self.label_15 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_15.setGeometry(QtCore.QRect(390, 30, 91, 21))
        self.label_15.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_12.setGeometry(QtCore.QRect(380, 50, 111, 131))
        self.label_12.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_16.setGeometry(QtCore.QRect(510, 30, 91, 21))
        self.label_16.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_13 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_13.setGeometry(QtCore.QRect(500, 50, 111, 131))
        self.label_13.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.pushButtonOffsetX = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonOffsetX.setGeometry(QtCore.QRect(520, 60, 75, 19))
        self.pushButtonOffsetX.setObjectName("pushButtonOffsetX")
        self.pushButtonOffsetY = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonOffsetY.setGeometry(QtCore.QRect(520, 100, 75, 19))
        self.pushButtonOffsetY.setObjectName("pushButtonOffsetY")
        self.pushButtonOffsetZ = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonOffsetZ.setGeometry(QtCore.QRect(520, 140, 75, 19))
        self.pushButtonOffsetZ.setObjectName("pushButtonOffsetZ")
        self.label_21 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_21.setGeometry(QtCore.QRect(630, 30, 91, 21))
        self.label_21.setStyleSheet("background-color: rgb(58, 255, 13);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBoxMoveCoordiante)
        self.label_22.setGeometry(QtCore.QRect(620, 50, 111, 131))
        self.label_22.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.textEditxAccuracyZ = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxAccuracyZ.setGeometry(QtCore.QRect(630, 140, 91, 31))
        self.textEditxAccuracyZ.setObjectName("textEditxAccuracyZ")
        self.textEditxAccuracyY = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxAccuracyY.setGeometry(QtCore.QRect(630, 100, 91, 31))
        self.textEditxAccuracyY.setObjectName("textEditxAccuracyY")
        self.textEditxAccuracyX = QtWidgets.QTextEdit(self.groupBoxMoveCoordiante)
        self.textEditxAccuracyX.setGeometry(QtCore.QRect(630, 60, 91, 31))
        self.textEditxAccuracyX.setObjectName("textEditxAccuracyX")
        self.pushButtonGetSensorData = QtWidgets.QPushButton(self.groupBoxMoveCoordiante)
        self.pushButtonGetSensorData.setGeometry(QtCore.QRect(740, 100, 101, 21))
        self.pushButtonGetSensorData.setObjectName("pushButtonGetSensorData")
        self.label_13.raise_()
        self.label_12.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.textEditxMove.raise_()
        self.textEdityMove.raise_()
        self.textEditzMove.raise_()
        self.pushButtonMovex.raise_()
        self.pushButtonMovey.raise_()
        self.pushButtonMovez.raise_()
        self.pushButtonGetx.raise_()
        self.pushButtonGety.raise_()
        self.pushButtonGetz.raise_()
        self.labelSensorX.raise_()
        self.labelSensorY.raise_()
        self.labelSensorZ.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.pushButtonOffsetX.raise_()
        self.pushButtonOffsetY.raise_()
        self.pushButtonOffsetZ.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.textEditxAccuracyZ.raise_()
        self.textEditxAccuracyY.raise_()
        self.textEditxAccuracyX.raise_()
        self.pushButtonGetSensorData.raise_()
        self.groupBoxAxisLimit = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxAxisLimit.setGeometry(QtCore.QRect(410, 40, 401, 151))
        self.groupBoxAxisLimit.setObjectName("groupBoxAxisLimit")
        self.label_14 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_14.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_14.setObjectName("label_14")
        self.label_17 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_17.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_18.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.label_18.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_18.setObjectName("label_18")
        self.pushButtonLimitGet = QtWidgets.QPushButton(self.groupBoxAxisLimit)
        self.pushButtonLimitGet.setGeometry(QtCore.QRect(310, 80, 81, 31))
        self.pushButtonLimitGet.setObjectName("pushButtonLimitGet")
        self.zMaxLimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.zMaxLimit.setGeometry(QtCore.QRect(90, 120, 91, 21))
        self.zMaxLimit.setText("")
        self.zMaxLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.zMaxLimit.setObjectName("zMaxLimit")
        self.xMaxLimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.xMaxLimit.setGeometry(QtCore.QRect(90, 40, 91, 21))
        self.xMaxLimit.setText("")
        self.xMaxLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.xMaxLimit.setObjectName("xMaxLimit")
        self.yMaxLimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.yMaxLimit.setGeometry(QtCore.QRect(90, 80, 91, 21))
        self.yMaxLimit.setText("")
        self.yMaxLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.yMaxLimit.setObjectName("yMaxLimit")
        self.zMinLimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.zMinLimit.setGeometry(QtCore.QRect(200, 120, 91, 21))
        self.zMinLimit.setText("")
        self.zMinLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.zMinLimit.setObjectName("zMinLimit")
        self.xMinLimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.xMinLimit.setGeometry(QtCore.QRect(200, 40, 91, 21))
        self.xMinLimit.setText("")
        self.xMinLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.xMinLimit.setObjectName("xMinLimit")
        self.yMinLimit = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.yMinLimit.setGeometry(QtCore.QRect(200, 80, 91, 21))
        self.yMinLimit.setText("")
        self.yMinLimit.setAlignment(QtCore.Qt.AlignCenter)
        self.yMinLimit.setObjectName("yMinLimit")
        self.label_19 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_19.setGeometry(QtCore.QRect(80, 30, 111, 131))
        self.label_19.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_20.setGeometry(QtCore.QRect(190, 30, 111, 131))
        self.label_20.setStyleSheet("background-color: rgb(255, 249, 189);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_20.raise_()
        self.label_19.raise_()
        self.label_14.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.pushButtonLimitGet.raise_()
        self.zMaxLimit.raise_()
        self.xMaxLimit.raise_()
        self.yMaxLimit.raise_()
        self.zMinLimit.raise_()
        self.xMinLimit.raise_()
        self.yMinLimit.raise_()
        self.checkBoxPLC = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxPLC.setGeometry(QtCore.QRect(210, 10, 51, 20))
        self.checkBoxPLC.setChecked(True)
        self.checkBoxPLC.setObjectName("checkBoxPLC")
        self.checkBoxSensor = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxSensor.setGeometry(QtCore.QRect(280, 10, 81, 20))
        self.checkBoxSensor.setChecked(True)
        self.checkBoxSensor.setObjectName("checkBoxSensor")
        self.groupBoxAxisSpeed_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxAxisSpeed_2.setGeometry(QtCore.QRect(0, 370, 381, 151))
        self.groupBoxAxisSpeed_2.setObjectName("groupBoxAxisSpeed_2")
        self.label_6 = QtWidgets.QLabel(self.groupBoxAxisSpeed_2)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_6.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBoxAxisSpeed_2)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_7.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBoxAxisSpeed_2)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.label_8.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_8.setObjectName("label_8")
        self.textEditXStep = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_2)
        self.textEditXStep.setGeometry(QtCore.QRect(80, 30, 91, 31))
        self.textEditXStep.setObjectName("textEditXStep")
        self.textEditYStep = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_2)
        self.textEditYStep.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.textEditYStep.setObjectName("textEditYStep")
        self.textEditZStep = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_2)
        self.textEditZStep.setGeometry(QtCore.QRect(80, 110, 91, 31))
        self.textEditZStep.setObjectName("textEditZStep")
        self.ButtonStepMoveX = QtWidgets.QPushButton(self.groupBoxAxisSpeed_2)
        self.ButtonStepMoveX.setGeometry(QtCore.QRect(180, 30, 89, 31))
        self.ButtonStepMoveX.setObjectName("ButtonStepMoveX")
        self.ButtonStepMoveY = QtWidgets.QPushButton(self.groupBoxAxisSpeed_2)
        self.ButtonStepMoveY.setGeometry(QtCore.QRect(180, 70, 89, 31))
        self.ButtonStepMoveY.setObjectName("ButtonStepMoveY")
        self.ButtonStepMoveZ = QtWidgets.QPushButton(self.groupBoxAxisSpeed_2)
        self.ButtonStepMoveZ.setGeometry(QtCore.QRect(180, 110, 89, 31))
        self.ButtonStepMoveZ.setObjectName("ButtonStepMoveZ")
        self.groupBoxAxisSpeed_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBoxAxisSpeed_3.setGeometry(QtCore.QRect(390, 370, 381, 151))
        self.groupBoxAxisSpeed_3.setObjectName("groupBoxAxisSpeed_3")
        self.label_29 = QtWidgets.QLabel(self.groupBoxAxisSpeed_3)
        self.label_29.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_29.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.groupBoxAxisSpeed_3)
        self.label_31.setGeometry(QtCore.QRect(10, 90, 67, 17))
        self.label_31.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_31.setObjectName("label_31")
        self.textEditBurningLoopTimes = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_3)
        self.textEditBurningLoopTimes.setGeometry(QtCore.QRect(80, 30, 91, 31))
        self.textEditBurningLoopTimes.setObjectName("textEditBurningLoopTimes")
        self.textEditBurningInterval = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_3)
        self.textEditBurningInterval.setGeometry(QtCore.QRect(80, 80, 91, 31))
        self.textEditBurningInterval.setObjectName("textEditBurningInterval")
        self.ButtonBurning = QtWidgets.QPushButton(self.groupBoxAxisSpeed_3)
        self.ButtonBurning.setGeometry(QtCore.QRect(220, 50, 89, 31))
        self.ButtonBurning.setObjectName("ButtonBurning")
        self.groupBoxAxisSpeed.raise_()
        self.pushButtonOpenPort.raise_()
        self.pushButtonClosePort.raise_()
        self.groupBoxMoveCoordiante.raise_()
        self.groupBoxAxisLimit.raise_()
        self.checkBoxPLC.raise_()
        self.checkBoxSensor.raise_()
        self.groupBoxAxisSpeed_2.raise_()
        self.groupBoxAxisSpeed_3.raise_()
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setGeometry(QtCore.QRect(30, 40, 81, 31))
        self.label_23.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(30, 90, 81, 31))
        self.label_24.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(30, 140, 81, 31))
        self.label_25.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_25.setObjectName("label_25")
        self.textEditFrequency = QtWidgets.QTextEdit(self.tab_4)
        self.textEditFrequency.setGeometry(QtCore.QRect(140, 40, 101, 31))
        self.textEditFrequency.setObjectName("textEditFrequency")
        self.textEditTime = QtWidgets.QTextEdit(self.tab_4)
        self.textEditTime.setGeometry(QtCore.QRect(140, 90, 101, 31))
        self.textEditTime.setObjectName("textEditTime")
        self.textEditSleepTime = QtWidgets.QTextEdit(self.tab_4)
        self.textEditSleepTime.setGeometry(QtCore.QRect(140, 140, 101, 31))
        self.textEditSleepTime.setObjectName("textEditSleepTime")
        self.ButtonAcquire = QtWidgets.QPushButton(self.tab_4)
        self.ButtonAcquire.setGeometry(QtCore.QRect(310, 90, 113, 32))
        self.ButtonAcquire.setObjectName("ButtonAcquire")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(450, 40, 91, 31))
        self.label_26.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(450, 140, 91, 31))
        self.label_27.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(450, 90, 91, 31))
        self.label_28.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_28.setObjectName("label_28")
        self.labelRollAverage = QtWidgets.QLabel(self.tab_4)
        self.labelRollAverage.setGeometry(QtCore.QRect(570, 40, 81, 31))
        self.labelRollAverage.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelRollAverage.setText("")
        self.labelRollAverage.setObjectName("labelRollAverage")
        self.labelPitchAverage = QtWidgets.QLabel(self.tab_4)
        self.labelPitchAverage.setGeometry(QtCore.QRect(570, 90, 81, 31))
        self.labelPitchAverage.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelPitchAverage.setText("")
        self.labelPitchAverage.setObjectName("labelPitchAverage")
        self.labelYawAverage = QtWidgets.QLabel(self.tab_4)
        self.labelYawAverage.setGeometry(QtCore.QRect(570, 140, 81, 31))
        self.labelYawAverage.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelYawAverage.setText("")
        self.labelYawAverage.setObjectName("labelYawAverage")
        self.groupBoxAxisSpeed_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBoxAxisSpeed_4.setGeometry(QtCore.QRect(20, 220, 391, 151))
        self.groupBoxAxisSpeed_4.setObjectName("groupBoxAxisSpeed_4")
        self.label_30 = QtWidgets.QLabel(self.groupBoxAxisSpeed_4)
        self.label_30.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_30.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_30.setObjectName("label_30")
        self.label_32 = QtWidgets.QLabel(self.groupBoxAxisSpeed_4)
        self.label_32.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_32.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBoxAxisSpeed_4)
        self.label_33.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.label_33.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_33.setObjectName("label_33")
        self.textEditXPLCOffset = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_4)
        self.textEditXPLCOffset.setGeometry(QtCore.QRect(80, 30, 91, 31))
        self.textEditXPLCOffset.setObjectName("textEditXPLCOffset")
        self.textEditYPLCOffset = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_4)
        self.textEditYPLCOffset.setGeometry(QtCore.QRect(80, 70, 91, 31))
        self.textEditYPLCOffset.setObjectName("textEditYPLCOffset")
        self.textEditZPLCOffset = QtWidgets.QTextEdit(self.groupBoxAxisSpeed_4)
        self.textEditZPLCOffset.setGeometry(QtCore.QRect(80, 110, 91, 31))
        self.textEditZPLCOffset.setObjectName("textEditZPLCOffset")
        self.pushButtonSetPLCOffset = QtWidgets.QPushButton(self.groupBoxAxisSpeed_4)
        self.pushButtonSetPLCOffset.setGeometry(QtCore.QRect(260, 60, 89, 41))
        self.pushButtonSetPLCOffset.setObjectName("pushButtonSetPLCOffset")
        self.groupBoxSetAxisLimit = QtWidgets.QGroupBox(self.tab_4)
        self.groupBoxSetAxisLimit.setGeometry(QtCore.QRect(450, 220, 401, 151))
        self.groupBoxSetAxisLimit.setObjectName("groupBoxSetAxisLimit")
        self.label_Axis = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.label_Axis.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.label_Axis.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_Axis.setObjectName("label_Axis")
        self.label_Yxis = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.label_Yxis.setGeometry(QtCore.QRect(10, 80, 67, 17))
        self.label_Yxis.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_Yxis.setObjectName("label_Yxis")
        self.label_Zxis = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.label_Zxis.setGeometry(QtCore.QRect(10, 120, 67, 17))
        self.label_Zxis.setStyleSheet("background-color: rgb(252, 233, 79);")
        self.label_Zxis.setObjectName("label_Zxis")
        self.pushButtonSetLimit = QtWidgets.QPushButton(self.groupBoxSetAxisLimit)
        self.pushButtonSetLimit.setGeometry(QtCore.QRect(310, 96, 81, 31))
        self.pushButtonSetLimit.setObjectName("pushButtonSetLimit")
        self.zMaxLimit_2 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.zMaxLimit_2.setGeometry(QtCore.QRect(90, 120, 91, 21))
        self.zMaxLimit_2.setText("")
        self.zMaxLimit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.zMaxLimit_2.setObjectName("zMaxLimit_2")
        self.xMaxLimit_2 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.xMaxLimit_2.setGeometry(QtCore.QRect(90, 40, 91, 21))
        self.xMaxLimit_2.setText("")
        self.xMaxLimit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.xMaxLimit_2.setObjectName("xMaxLimit_2")
        self.yMaxLimit_2 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.yMaxLimit_2.setGeometry(QtCore.QRect(90, 80, 91, 21))
        self.yMaxLimit_2.setText("")
        self.yMaxLimit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.yMaxLimit_2.setObjectName("yMaxLimit_2")
        self.zMinLimit_2 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.zMinLimit_2.setGeometry(QtCore.QRect(200, 120, 91, 21))
        self.zMinLimit_2.setText("")
        self.zMinLimit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.zMinLimit_2.setObjectName("zMinLimit_2")
        self.xMinLimit_2 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.xMinLimit_2.setGeometry(QtCore.QRect(200, 40, 91, 21))
        self.xMinLimit_2.setText("")
        self.xMinLimit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.xMinLimit_2.setObjectName("xMinLimit_2")
        self.yMinLimit_2 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.yMinLimit_2.setGeometry(QtCore.QRect(200, 80, 91, 21))
        self.yMinLimit_2.setText("")
        self.yMinLimit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.yMinLimit_2.setObjectName("yMinLimit_2")
        self.textEditSetXMaxLimit = QtWidgets.QTextEdit(self.groupBoxSetAxisLimit)
        self.textEditSetXMaxLimit.setGeometry(QtCore.QRect(100, 30, 91, 31))
        self.textEditSetXMaxLimit.setObjectName("textEditSetXMaxLimit")
        self.textEditSetXMinLimit = QtWidgets.QTextEdit(self.groupBoxSetAxisLimit)
        self.textEditSetXMinLimit.setGeometry(QtCore.QRect(210, 30, 91, 31))
        self.textEditSetXMinLimit.setObjectName("textEditSetXMinLimit")
        self.textEditSetYMinLimit = QtWidgets.QTextEdit(self.groupBoxSetAxisLimit)
        self.textEditSetYMinLimit.setGeometry(QtCore.QRect(210, 70, 91, 31))
        self.textEditSetYMinLimit.setObjectName("textEditSetYMinLimit")
        self.textEditSetYMaxLimit = QtWidgets.QTextEdit(self.groupBoxSetAxisLimit)
        self.textEditSetYMaxLimit.setGeometry(QtCore.QRect(100, 70, 91, 31))
        self.textEditSetYMaxLimit.setObjectName("textEditSetYMaxLimit")
        self.textEditSetZMinLimit = QtWidgets.QTextEdit(self.groupBoxSetAxisLimit)
        self.textEditSetZMinLimit.setGeometry(QtCore.QRect(210, 110, 91, 31))
        self.textEditSetZMinLimit.setObjectName("textEditSetZMinLimit")
        self.textEditSetZMaxLimit = QtWidgets.QTextEdit(self.groupBoxSetAxisLimit)
        self.textEditSetZMaxLimit.setGeometry(QtCore.QRect(100, 110, 91, 31))
        self.textEditSetZMaxLimit.setObjectName("textEditSetZMaxLimit")
        self.label_SetPasswd = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.label_SetPasswd.setGeometry(QtCore.QRect(320, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_SetPasswd.setFont(font)
        self.label_SetPasswd.setObjectName("label_SetPasswd")
        self.textEditSetAxisLimit = QtWidgets.QTextEdit(self.groupBoxSetAxisLimit)
        self.textEditSetAxisLimit.setGeometry(QtCore.QRect(310, 50, 81, 31))
        self.textEditSetAxisLimit.setObjectName("textEditSetAxisLimit")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("background-color: rgb(34, 194, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.labelErrorMessage = QtWidgets.QLabel(Form)
        self.labelErrorMessage.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.labelErrorMessage.setText("")
        self.labelErrorMessage.setObjectName("labelErrorMessage")
        self.verticalLayout.addWidget(self.labelErrorMessage)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        #*************** add acceleration and angles rate ***************
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(30, 400, 91, 31))
        self.label_34.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(30, 450, 91, 31))
        self.label_35.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(30, 500, 91, 31))
        self.label_36.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_36.setObjectName("label_28")
        self.labelXAcceleration = QtWidgets.QLabel(self.tab_4)
        self.labelXAcceleration.setGeometry(QtCore.QRect(140, 400, 81, 31))
        self.labelXAcceleration.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelXAcceleration.setText("")
        self.labelXAcceleration.setObjectName("labelXAcceleration")
        self.labelYAcceleration = QtWidgets.QLabel(self.tab_4)
        self.labelYAcceleration.setGeometry(QtCore.QRect(140, 450, 81, 31))
        self.labelYAcceleration.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelYAcceleration.setText("")
        self.labelYAcceleration.setObjectName("labelYAcceleration")
        self.labelZAcceleration = QtWidgets.QLabel(self.tab_4)
        self.labelZAcceleration.setGeometry(QtCore.QRect(140, 500, 81, 31))
        self.labelZAcceleration.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelZAcceleration.setText("")
        self.labelZAcceleration.setObjectName("labelZAcceleration")

        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(450, 400, 91, 31))
        self.label_37.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setGeometry(QtCore.QRect(450, 450, 91, 31))
        self.label_38.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setGeometry(QtCore.QRect(450, 500, 91, 31))
        self.label_39.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.label_39.setObjectName("label_39")
        self.labelXAnglesRate = QtWidgets.QLabel(self.tab_4)
        self.labelXAnglesRate.setGeometry(QtCore.QRect(570, 400, 81, 31))
        self.labelXAnglesRate.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelXAnglesRate.setText("")
        self.labelXAnglesRate.setObjectName("labelXAnglesRate")
        self.labelYAnglesRate = QtWidgets.QLabel(self.tab_4)
        self.labelYAnglesRate.setGeometry(QtCore.QRect(570, 450, 81, 31))
        self.labelYAnglesRate.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelYAnglesRate.setText("")
        self.labelYAnglesRate.setObjectName("labelYAnglesRate")
        self.labelZAnglesRate = QtWidgets.QLabel(self.tab_4)
        self.labelZAnglesRate.setGeometry(QtCore.QRect(570, 500, 81, 31))
        self.labelZAnglesRate.setStyleSheet("background-color: rgb(41, 255, 244);")
        self.labelZAnglesRate.setText("")
        self.labelZAnglesRate.setObjectName("labelZAnglesRate")

        self.label_SetPasswd_2 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.label_SetPasswd_2.setGeometry(QtCore.QRect(110, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_SetPasswd_2.setFont(font)
        self.label_SetPasswd_2.setObjectName("label_SetPasswd_2")
        self.label_SetPasswd_3 = QtWidgets.QLabel(self.groupBoxSetAxisLimit)
        self.label_SetPasswd_3.setGeometry(QtCore.QRect(223, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_SetPasswd_3.setFont(font)
        self.label_SetPasswd_3.setObjectName("label_SetPasswd_3")
        self.label_SetPasswd_4 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_SetPasswd_4.setGeometry(QtCore.QRect(100, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_SetPasswd_4.setFont(font)
        self.label_SetPasswd_4.setObjectName("label_SetPasswd_4")
        self.label_SetPasswd_5 = QtWidgets.QLabel(self.groupBoxAxisLimit)
        self.label_SetPasswd_5.setGeometry(QtCore.QRect(212, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_SetPasswd_5.setFont(font)
        self.label_SetPasswd_5.setObjectName("label_SetPasswd_5")
        self.AcquireAcceleration = QtWidgets.QPushButton(self.tab_4)
        self.AcquireAcceleration.setGeometry(QtCore.QRect(300, 450, 125, 32))
        self.AcquireAcceleration.setObjectName("AcquireAcceleration")


        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Bojay IMU"))
        self.label_4.setText(_translate("Form", "Bojay IMU UI V1.0"))
        self.pushButtonOpenPort.setText(_translate("Form", "OpenPort"))
        self.pushButtonClosePort.setText(_translate("Form", "ClosePort"))
        self.groupBoxAxisSpeed.setTitle(_translate("Form", "Axis Speed"))
        self.label.setText(_translate("Form", "X Axis"))
        self.label_3.setText(_translate("Form", "Y Axis"))
        self.label_5.setText(_translate("Form", "Z Axis"))
        self.pushButtonSpeedSet.setText(_translate("Form", "Set"))
        self.pushButtonSpeedGet.setText(_translate("Form", "Get"))
        self.groupBoxMoveCoordiante.setTitle(_translate("Form", "Move Coordinate"))
        self.label_9.setText(_translate("Form", "X Axis"))
        self.label_10.setText(_translate("Form", "Y Axis"))
        self.label_11.setText(_translate("Form", "Z Axis"))
        self.pushButtonMovex.setText(_translate("Form", "Move X"))
        self.pushButtonMovey.setText(_translate("Form", "Move Y"))
        self.pushButtonMovez.setText(_translate("Form", "Move Z"))
        self.pushButtonGetx.setText(_translate("Form", "Get X"))
        self.pushButtonGety.setText(_translate("Form", "Get Y"))
        self.pushButtonGetz.setText(_translate("Form", "Get Z"))
        self.label_15.setText(_translate("Form", "Sensor Data"))
        self.label_16.setText(_translate("Form", "Sensor Data"))
        self.pushButtonOffsetX.setText(_translate("Form", "Offset X"))
        self.pushButtonOffsetY.setText(_translate("Form", "Offset Y"))
        self.pushButtonOffsetZ.setText(_translate("Form", "Offset Z"))
        self.label_21.setText(_translate("Form", "Accuracy"))
        self.pushButtonGetSensorData.setText(_translate("Form", "Get sensor"))
        self.groupBoxAxisLimit.setTitle(_translate("Form", "Axis Limit"))
        self.label_14.setText(_translate("Form", "X Axis"))
        self.label_17.setText(_translate("Form", "Y Axis"))
        self.label_18.setText(_translate("Form", "Z Axis"))
        self.pushButtonLimitGet.setText(_translate("Form", "Get"))
        self.checkBoxPLC.setText(_translate("Form", "PLC"))
        self.checkBoxSensor.setText(_translate("Form", "Sensor"))
        self.groupBoxAxisSpeed_2.setTitle(_translate("Form", "Set step"))
        self.label_6.setText(_translate("Form", "X Axis"))
        self.label_7.setText(_translate("Form", "Y Axis"))
        self.label_8.setText(_translate("Form", "Z Axis"))
        self.ButtonStepMoveX.setText(_translate("Form", "Move X"))
        self.ButtonStepMoveY.setText(_translate("Form", "Move Y"))
        self.ButtonStepMoveZ.setText(_translate("Form", "Move Z"))
        self.groupBoxAxisSpeed_3.setTitle(_translate("Form", "Burning"))
        self.label_29.setText(_translate("Form", "LoopTimes"))
        self.label_31.setText(_translate("Form", "Interval"))
        self.ButtonBurning.setText(_translate("Form", "Burning"))
        self.groupBox.setTitle(_translate("Form", "password"))
        self.pushButtonSetPosition.setText(_translate("Form", "SetPosition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Tab 1"))
        self.label_23.setText(_translate("Form", "Frequency"))
        self.label_24.setText(_translate("Form", "Time"))
        self.label_25.setText(_translate("Form", "SleepTime"))
        self.ButtonAcquire.setText(_translate("Form", "Acquire"))
        self.label_26.setText(_translate("Form", "Roll Average"))
        self.label_27.setText(_translate("Form", "Yaw Average"))
        self.label_28.setText(_translate("Form", "Pitch Average"))
        self.groupBoxAxisSpeed_4.setTitle(_translate("Form", "PLC offset"))
        self.label_30.setText(_translate("Form", "X Axis"))
        self.label_32.setText(_translate("Form", "Y Axis"))
        self.label_33.setText(_translate("Form", "Z Axis"))
        self.pushButtonSetPLCOffset.setText(_translate("Form", "Set"))
        self.groupBoxSetAxisLimit.setTitle(_translate("Form", "Axis Limit"))
        self.label_Axis.setText(_translate("Form", "X Axis"))
        self.label_Yxis.setText(_translate("Form", "Y Axis"))
        self.label_Zxis.setText(_translate("Form", "Z Axis"))
        self.pushButtonSetLimit.setText(_translate("Form", "Set"))
        self.label_SetPasswd.setText(_translate("Form", "password"))

        self.label_SetPasswd_2.setText(_translate("Form", "MaxLimit"))
        self.label_SetPasswd_3.setText(_translate("Form", "MinLimit"))
        self.label_SetPasswd_4.setText(_translate("Form", "MaxLimit"))
        self.label_SetPasswd_5.setText(_translate("Form", "MinLimit"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Tab 2"))
        self.label_2.setText(_translate("Form", "Developed by Tony"))
        #*************** add acceleration and angles rate ***************
        self.label_34.setText(_translate("Form", "X Acceleration"))
        self.label_35.setText(_translate("Form", "Y Acceleration"))
        self.label_36.setText(_translate("Form", "Z Acceleration"))
        self.label_37.setText(_translate("Form", "X Angles Rate"))
        self.label_38.setText(_translate("Form", "Y Angles Rate"))
        self.label_39.setText(_translate("Form", "Z Angles Rate"))
        self.AcquireAcceleration.setText(_translate("Form", "Acquire Acceleration"))
